# Generated by Django 2.1.3 on 2018-11-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181123_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risks',
            old_name='format',
            new_name='data',
        ),
    ]
