# Generated by Django 2.1.3 on 2018-11-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20181123_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risks',
            name='risk_type',
        ),
        migrations.DeleteModel(
            name='Risks',
        ),
    ]
