# Generated by Django 2.1.3 on 2018-11-28 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_auto_20181127_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskTypes')),
            ],
        ),
    ]
